version: "3.9"

services:
  mongo:
    image: mongo:6.0.9
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=stongpassword

volumes:
  dbdata6: