version: "3.9"

services:

                    # Beaware that 5.7 Mysql DB Container root is only accessible from Localhost
  
    mysql:
      image: mysql:5.7.43
      container_name: mysql
      privileged: true
      volumes:
        - '$PWD/mysql/data:/var/lib/mysql'
        #- '$PWD/mysql/mysqld.cnf:/etc/my.cnf'
        #- '$PWD/mysql/gloabals.cnf:/etc/mysql/mysql.conf.d/gloabals.cnf'
      restart: always
        #      expose:
        # - "3306"
      ports:
        - 3306:3306
      env_file:
        - .env
      # network_mode: host
      healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
        timeout: 20s
        retries: 3

    db_seeder:
      image: mysql:5.7.43
      # network_mode: host
      volumes:
        - $PWD/user.sql:/user.sql
        - $PWD/script.sh:/script.sh
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # entrypoint: [ "bash", "-c", "sleep 10 && mysql --user=root --host=mysql --password=${MYSQL_ROOT_PASSWORD} --port=3306 < /user.sql && exit"]
      entrypoint: [ "bash", "-c", "sleep 10 && MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} /script.sh && exit"]
      # entrypoint: [ "bash", "-c", "sleep infinity"]
      depends_on:
        mysql:
          condition: service_healthy